### ISSUE TITLE
[e10s] Doesn't work with enabled Electrolysis (multi-process mode)

### ISSUE THREAD

**Issue by Infocatcher** [Infocatcher/Private_Tab#162]
See http://forums.mozillazine.org/viewtopic.php?p=13832477#p13832477
Also it's hard to work without fixed <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1051238">bug 1051238 – frame scripts are cached forever & thus can't be updated restartless</a>.
Docs: https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox

Related issues:
- [x] #181: Open Link in New Private Tab Broken [Ffx 41] [OSX] [E10s]
- [x] #182: Private Tab Shortcut Broken [Ffx 41] [OSX]
- [x] #208: [e10s] Get rid "unsafe CPOW usage", this raise an error in Firefox 47.0a1+
- [x] #211: [e10s] Private protocol doesn't work in multi-process mode
- [x] #213: [e10s] Use only one frame script for communications with remote tabs

**Comment by Infocatcher** [comment]
Also "private:" protocol doesn't work at all due to <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=940206">bug 940206 – nsIWebContentHandlerRegistrar::registerProtocolHandler doesn't work in e10s</a>

**Comment by Infocatcher** [comment]
Also on Nightly there is some wrappers around `removeEventListener()` (even with disabled e10s!), that doesn't work sometimes.
Looks like `<em:multiprocessCompatible>true</em:multiprocessCompatible>` in `install.rdf` fixes that. But this is strange to set that flag for <ins>disabled</ins> e10s (because still doesn't work for enabled e10s).

**Comment by siavash119** [comment]
With Private Tab enabled, I can't change favicon with javascript in firefox e10s tabs (private or not). The javascript works fine and the tabbar in non-e10s tabs. Here's a quick test script you can run in scratchpad:

(function() {
    var link = document.createElement('link');
    link.type = 'image/x-icon';
    link.rel = 'shortcut icon';
    link.href = 'http://www.stackoverflow.com/favicon.ico';
    document.getElementsByTagName('head')[0].appendChild(link);
}());

this may be a good resource: https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox

**Comment by Infocatcher** [comment]
I added a workaround for favicons: 06eab93cc94e6e28732673f325654afbfd238cf4
This is ugly way (and tab will be assumed as non-private), but looks like there is no way to detect privacy state during some `gBrowser.setIcon()` calls.

**Comment by Infocatcher** [comment]
Some researches:
```js
	toggleTabPrivate: function(tab, isPrivate, _silent) {
		var window = tab.ownerDocument.defaultView;
		var privacyContext = this.getTabPrivacyContext(tab);
		if(!privacyContext) { // Electrolysis
			//~ todo: use content script or something else to handle remove browser
			_log("toggleTabPrivate(): getTabPrivacyContext() failed, will wait");
			var observe = function(subject, topic, data) {
				// Note: subject == tab.linkedBrowser.contentWindow is always false. Don't ask me, why.
				_log("Created content document: " + subject.location);
				if(subject.document == tab.linkedBrowser.contentDocument) {
					Services.obs.removeObserver(observe, topic);
					_log("Created content document: " + subject.location + "\nLet's try again");
					this.toggleTabPrivate(tab, isPrivate, _silent);
				}
			}.bind(this);
			Services.obs.addObserver(observe, "content-document-global-created", false);
			return;
		}
```
And what we see? Cookies was already sent. :(

**Comment by Infocatcher** [comment]
Also too late to toggle private state:
```js
		if(!privacyContext) { // Electrolysis
			//~ todo: use content script or something else to handle remote browser
			_log("toggleTabPrivate(): getTabPrivacyContext() failed, will wait");
			var browser = tab.linkedBrowser;
			var onTabReady = function(e) {
				browser.removeEventListener("DOMWindowCreated", onTabReady, true);
				_log("Received " + e.type + ", let's try again");
				this.toggleTabPrivate(tab, isPrivate, _silent);
			}.bind(this);
			browser.addEventListener("DOMWindowCreated", onTabReady, true);
			return;
		}
```

**Comment by Infocatcher** [comment]
Test version: <a href="http://infocatcher.ucoz.net/temp/pt/private_tab-0.1.8pre-fx-sm.xpi">private_tab-0.1.8pre-fx-sm.xpi</a> (<a href="https://github.com/Infocatcher/Private_Tab/tree/22b4aebe17893997b376d9ac9f47f120e7d53a22">source code</a>).
Please note: many things may not work, but at least some basic things was fixed.

**Comment by bogas04** [comment]
Favicons aren't displayed for tabs when Private Tabs in enabled on e10s latest nightlies. I've tried refreshing my profile, doesn't help

**Comment by Infocatcher** [comment]
> Favicons aren't displayed for tabs when Private Tabs in enabled on e10s latest nightlies.

Works fine for me...
Please try latest development version:
<a href="http://infocatcher.ucoz.net/temp/pt/private_tab-0.1.9.2pre2-fx-sm.xpi">private_tab-0.1.9.2pre2-fx-sm.xpi</a> (<a href="https://github.com/Infocatcher/Private_Tab/tree/6ae4a746353516ece0f3f442d6e109a7cd9783ea">source code</a>)

**Comment by sebadorn** [comment]
I had the same problem: Firefox 48.0a2 with e10s enabled and Private Tab 0.1.9.1.
Now with 0.1.9.2pre2 favicons are working again.

**Comment by anewuser** [comment]
@Infocatcher If possible, please try to join their IRC channel on Tuesdays to report the problems still affecting Private Tab: 

* https://blog.mozilla.org/addons/2016/08/02/multi-process-firefox-and-add-ons-a-call-to-action/
* https://developer.mozilla.org/Add-ons/Working_with_multiprocess_Firefox#Adapting_to_Multiple_Processes
* https://atsay.github.io/e10s_office_hours/

**Comment by Infocatcher** [comment]
Most of e10s-related bugs should be fixed:
https://addons.mozilla.org/addon/private-tab/versions/0.2.0

**Comment by anewuser** [comment]
@Infocatcher That's great news. Thank you very much for your work on this extension and for not giving up despite all changes done by Mozilla. It's the one thing that keeps me on Firefox.
